name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics (dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Suhel-Shaikh-Mohammad

          # ---- Base & theme ----
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Asia/Kolkata
          config_background: dark

          # ---- Contribution calendar ----
          plugin_isocalendar: no

          # ---- Contribution breakdown ----
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_filter: all

          # ---- LOC & languages ----
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines
          plugin_languages_limit: 8
